// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTcLq9WXEAsw3SkjNCaRT_OK7ysCNtVE',
    appId: '1:916972821454:web:e0726b0adc145f4c37e99f',
    messagingSenderId: '916972821454',
    projectId: 'assignment-3fa68',
    authDomain: 'assignment-3fa68.firebaseapp.com',
    databaseURL: 'https://assignment-3fa68-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-3fa68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBayiH8XRLijTQozTxIWUUF2R792U17c',
    appId: '1:916972821454:android:168731c1e7a113d437e99f',
    messagingSenderId: '916972821454',
    projectId: 'assignment-3fa68',
    databaseURL: 'https://assignment-3fa68-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-3fa68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldWPmTRy6sttzHelPpPQsrvKIyphB8S8',
    appId: '1:916972821454:ios:7d611f45a491c6c437e99f',
    messagingSenderId: '916972821454',
    projectId: 'assignment-3fa68',
    databaseURL: 'https://assignment-3fa68-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-3fa68.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAldWPmTRy6sttzHelPpPQsrvKIyphB8S8',
    appId: '1:916972821454:ios:ba746acef01b982337e99f',
    messagingSenderId: '916972821454',
    projectId: 'assignment-3fa68',
    databaseURL: 'https://assignment-3fa68-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-3fa68.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
